### ISSUE TITLE
PubChem outlink to RDF accordion

### ISSUE THREAD

**Issue by jaygray0919** [truett-software/Knowledge-Graph#11]
The remote file is here:
* story_outlink/NIH-NCBI-pubchem-RDF/_pubchem-RDF-accordion/index.html

**Comment by truett-software** [comment]
We have checked this file in github folder

- "story_outlink/NIH-NCBI-pubchem-RDF/_pubchem-RDF-accordion/index.html"URL

and updated in KG (test branch) - index.html file 

- https://github.com/truett-software/story-knowledge-graph/blob/b6c9117e6a0c34e6ac32aaa329a0ad667c247032/docs/story/index.html#L3800C17-L3800C17


It didn't work on the live server instances. but, it works when i run this file in my local folder(Pc).

- https://truett-software.github.io/story-knowledge-graph/story_outlink/NIH-NCBI-pubchem-RDF/_pubchem-RDF-accordion/index.html

**Comment by jaygray0919** [comment]
i this this link         <a href="/story-knowledge-graph/story_outlink/NIH-NCBI-pubchem-RDF/_pubchem-RDF-accordion/index.html">More about PubChem RDF</a>

should be `"../story_outlink/NIH-NCBI-pubchem-RDF/_pubchem-RDF-accordion/index.html"`

**Comment by truett-software** [comment]
We have implemented the outlink href link like this "../story_outlink/NIH-NCBI-pubchem-RDF/_pubchem-RDF-accordion/index.html"

Please check this 
- https://github.com/truett-software/story-knowledge-graph/blob/6f5b3966fe36a8ee1d23a3bcd63105eb341ee16c/docs/story/index.html#L3800C33-L3800C33

but this is not working, can you please recheck it.
- kg-37 - https://truett-software.github.io/story-knowledge-graph/docs/story/

**Comment by jaygray0919** [comment]
I don't understand this completely.
First, i see a branch `6f5b396` above - is that the branch used to build https://truett-software.github.io/story-knowledge-graph/docs/story/ ?

An work-around:
copy
* https://github.com/truett-software/story-knowledge-graph/blob/qa-231207/story_outlink/NIH-NCBI-pubchem-RDF/_pubchem-RDF-accordion/index.html

to
* https://github.com/truett-software/story-knowledge-graph/tree/qa-231207/docs/story/37

and reset the story/index.html link to `/37/index.html`

that may eliminate the problems with relative locations (`../`)

do relative locations work in other statements?

**Comment by truett-software** [comment]
For your kind info,

As per your comments 

We have copied this index.html

- https://github.com/truett-software/story-knowledge-graph/blob/qa-231207/story_outlink/NIH-NCBI-pubchem-RDF/_pubchem-RDF-accordion/index.html

and we moved to this folder

- https://github.com/truett-software/story-knowledge-graph/tree/test/docs/story/37

we have implemented it in the index.html (test branch)

- https://github.com/truett-software/story-knowledge-graph/blob/edd0f0a5f74d6745a5a8ac573e0c6c32f5dc0e4f/docs/story/index.html#L3800

now its running correctly in instances. Please check it

-  https://truett-software.github.io/story-knowledge-graph/docs/story/
