### ISSUE TITLE
normalization

### ISSUE THREAD

**Issue by truett-software** [truett-software/Knowledge-Graph#12]
We have checked the main branch docs/story/index.html file, 

1. the specific slides images are called in folder format like(./19/why-knowledge-graphs-w818-h428.svg) we leave it as is or we will change it like this (https://truett-software.github.io/story-knowledge-graph/docs/story/19/why-knowledge-graphs-w818-h428.svg) please confirm us.

2. background images: all background images called like this
"https://github.com/truett-software/story-knowledge-graph/blob/99346ab2b718be69b37c9e3f6f491a82a2540ce8/docs/story/index.html#L2080C16-L2080C45"
this "fractal-noise-w1000-h1000.svg" file is not there in file folder. Can you share that svg we will implement it.

3. localize- 
    publisher-logo-src="https://ontomatica.io/static/image/logo/onto-symbol-w252-h252.svg"
    poster-portrait-src="https://benetta.net/media/background-svg/background-sun-tornado-w2000-h1500.svg"
    poster-square-src="https://benetta.net/media/background-svg/background-sun-tornado-w2000-h1500.svg"
    poster-landscape-src="https://benetta.net/media/background-svg/background-sun-tornado-w2000-h1500.svg"
    Please share this svg file also.

**Comment by jaygray0919** [comment]
Don't worry about #3 now. This is "my" TODO - not sure yet what to do.

Re #1. You should not need to change any relative URL. They should work AS-IS on github.io

You have #2 in Sowa: https://github.com/truett-software/story-sowa/blob/main/docs/story/background/background-fractal-noise-w1650-h1500.webp

**Comment by truett-software** [comment]
Hi Jay,

For your kind info, we have reviewed the above comments in the github issue.

We will rework on Knowledge Graph normalization. Once we complete or if we
have any doubts, we will create a new issue or comment on the existing
issue.

Thank you!

*Thanks & Regards,*
*Truett Software*
*https://truettsoftware.com <https://truettsoftware.com>*
*Email ID: ***@***.*** ***@***.***>*
*Skype: **TruettSoftware*
